### ISSUE TITLE
Export as JSON per line

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice_file_export#1]
This module needs a corresponding change to allow exporting data as 1 JSON record per line as an option similar to what was done for teraslice_file_import.

The parameter should be named `output_format`.

The options should be:
 * `json_array` - this is the current behavior and the default.
 * `json_lines` - One JSON record per line

We'll likely add additional formats in the future.

**Comment by jsnoble** [comment]
this is already resolved, in a previous commit, though output_format has changed to just format
